// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------

import type { UseReadContractParameters } from "wagmi";
import { useReadContract } from "wagmi";

import { TokenABI } from "@/lib/abi/token";

import { readContractQueryOptions } from "wagmi/query";
import { config } from "@/wagmi/config";
import { queryClient } from "@/lib/react-query";

export const getOwnerQueryOptions = ({
  address,
  chainId,
}: {
  address: `0x${string}`;
  chainId?: number;
}) =>
  readContractQueryOptions(config, {
    abi: TokenABI,
    address,
    functionName: "owner",
    chainId,
  });

type QueryOptions = UseReadContractParameters<
  typeof TokenABI,
  "owner"
>["query"];

export const fetchOwner = ({
  address,
  chainId,
}: {
  address: `0x${string}`;
  chainId?: number;
}) => queryClient.fetchQuery(getOwnerQueryOptions({ address, chainId }));

export const useOwner = (
  { address, chainId }: { address?: `0x${string}`; chainId?: number },
  options: QueryOptions = { enabled: true },
) => {
  return useReadContract({
    abi: TokenABI,
    address,
    functionName: "owner",
    chainId,

    query: { ...options, enabled: address && options?.enabled },
  });
};

// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------
