// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------

import type { UseReadContractParameters } from "wagmi";
import { useReadContract } from "wagmi";

import { TokenABI } from "@/lib/abi/token";

import { readContractQueryOptions } from "wagmi/query";
import type { AppChainId } from "@/wagmi/config";
import { config } from "@/wagmi/config";
import { queryClient } from "@/lib/react-query";

export const getNameQueryOptions = ({
  address,
  chainId,
}: {
  address: `0x${string}`;
  chainId?: AppChainId;
}) =>
  readContractQueryOptions(config, {
    abi: TokenABI,
    address,
    functionName: "name",
    chainId,
  });

type QueryOptions = UseReadContractParameters<typeof TokenABI, "name">["query"];

export const fetchName = ({
  address,
  chainId,
}: {
  address: `0x${string}`;
  chainId?: AppChainId;
}) => queryClient.fetchQuery(getNameQueryOptions({ address, chainId }));

export const useName = (
  { address, chainId }: { address?: `0x${string}`; chainId?: AppChainId },
  options: QueryOptions = { enabled: true },
) => {
  return useReadContract({
    abi: TokenABI,
    address,
    functionName: "name",
    chainId,

    query: { ...options, enabled: address && options?.enabled },
  });
};

// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------
