// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------

import type { UseReadContractParameters } from "wagmi";
import { useReadContract } from "wagmi";
import { isUndefined } from "lodash-es";
import { TokenABI } from "@/lib/abi/token";
import type { AbiInputsToParams } from "@/lib/contract-interactions/utils";
import {
  paramsToArray,
  extractAbiFunction,
} from "@/lib/contract-interactions/utils";
import type { ExtractAbiFunction } from "abitype";
import { readContractQueryOptions } from "wagmi/query";
import type { AppChainId } from "@/wagmi/config";
import { config } from "@/wagmi/config";
import { queryClient } from "@/lib/react-query";

type Fn = ExtractAbiFunction<typeof TokenABI, "allowance">;
const abiFunction = extractAbiFunction(TokenABI, "allowance");

export const getAllowanceQueryOptions = (
  { address, chainId }: { address: `0x${string}`; chainId?: AppChainId },
  params: AbiInputsToParams<Fn["inputs"]>,
) =>
  readContractQueryOptions(config, {
    abi: TokenABI,
    address,
    functionName: "allowance",
    chainId,
    args: paramsToArray({ params, abiFunction }),
  });

type QueryOptions = UseReadContractParameters<
  typeof TokenABI,
  "allowance"
>["query"];

export const fetchAllowance = (
  { address, chainId }: { address: `0x${string}`; chainId?: AppChainId },
  params: AbiInputsToParams<Fn["inputs"]>,
) =>
  queryClient.fetchQuery(
    getAllowanceQueryOptions({ address, chainId }, params),
  );

export const useAllowance = (
  { address, chainId }: { address?: `0x${string}`; chainId?: number },
  params: AbiInputsToParams<Fn["inputs"]>,
  options: QueryOptions = { enabled: true },
) => {
  const args = paramsToArray({ params, abiFunction });

  return useReadContract({
    abi: TokenABI,
    address,
    functionName: "allowance",
    chainId,
    args,
    query: {
      ...options,
      enabled:
        address && options?.enabled && args.every((arg) => !isUndefined(arg)),
    },
  });
};

// ------------------------------------------------
// This file is auto-generated by scripts/createReadsERC20.js
// ------------------------------------------------
