name: Build & deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      VITE_ROLLUP_A_CHAIN_ID: "11113"
      VITE_ROLLUP_B_CHAIN_ID: "22224"
      VITE_HOODI_CHAIN_ID: "560048"
      VITE_ROLLUP_A_RPC_HTTP: '["https://rpc-a.testnet.compose.network"]'
      VITE_ROLLUP_B_RPC_HTTP: '["https://rpc-b.testnet.compose.network"]'
      VITE_HOODI_RPC_HTTP: '["${{ secrets.COMPOSE_WEB_DEMO_HOODI_RPC_HTTP }}"]'
      VITE_MAINNET_RPC_HTTP: '["https://eth.llamarpc.com"]'
      VITE_POLYGON_RPC_HTTP: '["https://polygon-rpc.com"]'
      VITE_ROLLUP_A_BLOCK_EXPLORER_URL: "https://rollup-a.explorer.testnet.compose.network"
      VITE_ROLLUP_B_BLOCK_EXPLORER_URL: "https://rollup-b.explorer.testnet.compose.network"
      VITE_HOODI_BRIDGE_ADDRESS: "0xa9d7542e70822721ef3430ac43016c868d8d51a0"
      VITE_BRIDGE_HOODI_TO_ROLLUP_A: "0xa9d7542e70822721ef3430ac43016c868d8d51a0"
      VITE_BRIDGE_HOODI_TO_ROLLUP_B: "0x5c36beee62a1cebafc01ac925bc01400c2d18366"
      VITE_ROLLUP_A_KERNEL_IMPL: "0x317A2D4564778A585BAd21376dC1ca65b75ccC6a"
      VITE_ROLLUP_A_KERNEL_FACTORY: "0xdEF4343958B5dE047bddEFaB5Fa8F9Ff898890e5"
      VITE_ROLLUP_A_MULTICHAIN_VALIDATOR: "0x8aB3f6935399e1c10419cA2C93d60901a256b7e3"
      VITE_ROLLUP_A_META_FACTORY: "0x54db674c515e5fdec3f91345bc2fdafafd8b3b8a"
      VITE_ROLLUP_B_KERNEL_IMPL: "0x317A2D4564778A585BAd21376dC1ca65b75ccC6a"
      VITE_ROLLUP_B_KERNEL_FACTORY: "0xdEF4343958B5dE047bddEFaB5Fa8F9Ff898890e5"
      VITE_ROLLUP_B_MULTICHAIN_VALIDATOR: "0x8aB3f6935399e1c10419cA2C93d60901a256b7e3"
      VITE_ROLLUP_B_META_FACTORY: "0x54db674c515e5fdec3f91345bc2fdafafd8b3b8a"
      VITE_ROLLUP_A_BRIDGE_ADDRESS: "0x1388C9619aCCcd1dfff0234626EDDA61413Be74e"
      VITE_ROLLUP_B_BRIDGE_ADDRESS: "0x1388C9619aCCcd1dfff0234626EDDA61413Be74e"
      VITE_BRIDGE_TOKEN_ADDRESS: "0x70CF90476d253224672939ad6824BAab78Ac8E23"
      VITE_WETH_ADDRESS: "0x29dDf1a92069c4c170A63032C93c2aE66C359Bf9"
      VITE_USDC_ADDRESS: "0x0F5808d4776E7fB10293f2DCd6dA3073b8Dad970"
      VITE_SSV_ADDRESS: "0x969b0ad5ffa2376E8C0f5e413D510a056416D627"
      VITE_ROLLUP_B_SWAP_ADDRESS: "0xeF71C814296712f97D53dD2A32d59B70Ad8593dc"
      VITE_PAYMASTER_URL: "https://paymaster.testnet.compose.network"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install packages
        run: pnpm install

      - name: Setup swap
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 4

      - name: Run stage webapp build
        env:
          NODE_OPTIONS: --max-old-space-size=2048
        run:
          pnpm -r --workspace-concurrency=1 build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3
        with:
          role-to-assume: ${{ secrets.COMPOSE_WEB_DEMO_PRODUCTION_AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload files to S3
        run: |
          aws s3 cp ./build s3://${{ secrets.COMPOSE_WEB_DEMO_PRODUCTION_AWS_S3_BUCKET }} --recursive
