name: Build & deploy

on:
  push:
    branches:
      - 'stage'

  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      VITE_ROLLUP_A_CHAIN_ID: "77777"
      VITE_ROLLUP_B_CHAIN_ID: "88888"
      VITE_HOODI_CHAIN_ID: "560048"
      VITE_ROLLUP_A_RPC_HTTP: '["https://rollup-rpc-1.stage.ops.ssvlabsinternal.com"]'
      VITE_ROLLUP_B_RPC_HTTP: '["https://rollup-rpc-2.stage.ops.ssvlabsinternal.com"]'
      VITE_HOODI_RPC_HTTP: '["https://ethereum-hoodi-rpc.publicnode.com/d8a2cc6e7483872e917d7899f9403d738b001c80e37d66834f4e40e9efb54a27"]'
      VITE_MAINNET_RPC_HTTP: '["https://eth.llamarpc.com"]'
      VITE_POLYGON_RPC_HTTP: '["https://polygon-rpc.com"]'
      VITE_ROLLUP_A_BLOCK_EXPLORER_URL: "https://blockscout-rollup-1.stage.ops.ssvlabsinternal.com/"
      VITE_ROLLUP_B_BLOCK_EXPLORER_URL: "https://blockscout-rollup-2.stage.ops.ssvlabsinternal.com/"
      VITE_HOODI_BRIDGE_ADDRESS: "0x9adb5dba4f55d7ea921f34e98dc492b3a2ced734"
      VITE_BRIDGE_HOODI_TO_ROLLUP_A: "0xe6456c49bae7ff20bee0d01948d6d0f82dd821e9"
      VITE_BRIDGE_HOODI_TO_ROLLUP_B: "0x9adb5dba4f55d7ea921f34e98dc492b3a2ced734"
      VITE_ROLLUP_A_KERNEL_IMPL: "0x1ff48513f8722113ab840fdfd1866957d08bd5d2"
      VITE_ROLLUP_A_KERNEL_FACTORY: "0xcfb519af7e3e4b772c619ed12bcdc7d758ac6ee6"
      VITE_ROLLUP_A_MULTICHAIN_VALIDATOR: "0x5e729b0d9d35fa3bd7ace526437151ec9e1d5929"
      VITE_ROLLUP_A_META_FACTORY: "0x54db674c515e5fdec3f91345bc2fdafafd8b3b8a"
      VITE_ROLLUP_B_KERNEL_IMPL: "0x1ff48513f8722113ab840fdfd1866957d08bd5d2"
      VITE_ROLLUP_B_KERNEL_FACTORY: "0xcfb519af7e3e4b772c619ed12bcdc7d758ac6ee6"
      VITE_ROLLUP_B_MULTICHAIN_VALIDATOR: "0x5e729b0d9d35fa3bd7ace526437151ec9e1d5929"
      VITE_ROLLUP_B_META_FACTORY: "0x54db674c515e5fdec3f91345bc2fdafafd8b3b8a"
      VITE_ROLLUP_A_BRIDGE_ADDRESS: "0x31c57E2910496e46Bb883EDeb1eB2bee8E3Ee82C"
      VITE_ROLLUP_B_BRIDGE_ADDRESS: "0x31c57E2910496e46Bb883EDeb1eB2bee8E3Ee82C"
      VITE_BRIDGE_TOKEN_ADDRESS: "0x4c77De11C15d8b5e2584e67e2E6E1Ec7A78B0b5b"
      VITE_WETH_ADDRESS: "0x356dA0CBA100a69B3FD3F2Ce4871B7e3921E7553"
      VITE_USDC_ADDRESS: "0xeA0DB94b4c702d9cA0Fcc65715A035B24dF3452D"
      VITE_SSV_ADDRESS: "0x79155fb8d8dE01522bE1Cbd17e538966d78d1565"
      VITE_ROLLUP_B_SWAP_ADDRESS: "0x70f2e907bf467E28A96A2e314B5200c2B144b76c"
      VITE_PAYMASTER_URL: "https://paymaster.stage.ops.ssvlabsinternal.com"
      VITE_ROLLUP_A_UNISWAP_SSV_USDC: "0x0458D337e79AB5B45Ed10FF485Bd44dB45Cea630"
      VITE_ROLLUP_A_UNISWAP_WETH_SSV: "0xcA54C63a2642F365c93a07f6C602cb59E65edfa0"
      VITE_ROLLUP_A_UNISWAP_WETH_USDC: "0xAD40315aB540C32f7622890327F8F04843b93bC6"
      VITE_ROLLUP_A_UNISWAP_WETH_LINK: "0x39d08C6A693A98C3b4Cc72A60f300a4d1563e3c2"
      VITE_ROLLUP_A_UNISWAP_LINK_USDC: "0xBB39b9efB4A1Be5F11D3099526304BEa6ac1b62a"
      VITE_ROLLUP_A_UNISWAP_SSV_LINK: "0x3284da8e0ac8820A5e28B86c96715BA1bB857E6A"
      VITE_ROLLUP_B_UNISWAP_SSV_USDC: "0x98ebe29704d1dCac104C0613f7914e8B9cE4e0B4"
      VITE_ROLLUP_B_UNISWAP_WETH_SSV: "0xF0c0Aa0B450C0c1330B2fa6fdb7659aCc8A1Bff8"
      VITE_ROLLUP_B_UNISWAP_WETH_USDC: "0xb0a530987f12Dfe68D65C797f573323fD40436e2"
      VITE_ROLLUP_B_UNISWAP_DAI_WETH: "0x33A4Ab36203716E5E3f6B06907f40AeA27E31672"
      VITE_ROLLUP_B_UNISWAP_DAI_USDC: "0xa2F3BA27D7b938f560F440280B2786CC1a39a145"
      VITE_ROLLUP_B_UNISWAP_DAI_SSV: "0x3e8a3ADb7A31dc74f705b366F8bdA1ff09843f84"
      VITE_ROLLUP_A_UNISWAP_V3_CORE_FACTORY_ADDRESS: "0xCeC51b89502C50AeaCBFa9424D84C138a50288e6"
      VITE_ROLLUP_A_UNISWAP_MULTICALL2_ADDRESS: "0x648c0af7Fb54d80ca8B96e2Bd4bDbf829e5FF06B"
      VITE_ROLLUP_A_UNISWAP_PROXY_ADMIN_ADDRESS: "0x70f67e7bCac4aaf3A353AB342b14Fd3fAFBFae7B"
      VITE_ROLLUP_A_UNISWAP_TICK_LENS_ADDRESS: "0x06Eeba75cE17F0e863D4D7D2a4e3aA284F9F1A79"
      VITE_ROLLUP_A_UNISWAP_NFT_DESCRIPTOR_LIBRARY_ADDRESS_V1_3_0: "0xC1DebA0859fB7C55394ADC9cc67155805B209b0D"
      VITE_ROLLUP_A_UNISWAP_NONFUNGIBLE_TOKEN_POSITION_DESCRIPTOR_ADDRESS_V1_3_0: "0x96587956CAAee8fB7a8aB4c6Ecf84C9Bb8FbbbA6"
      VITE_ROLLUP_A_UNISWAP_DESCRIPTOR_PROXY_ADDRESS: "0xe24b538dd9aeDf7f01bD56603A1e07B4C72B8Ce8"
      VITE_ROLLUP_A_UNISWAP_NONFUNGIBLE_TOKEN_POSITION_MANAGER_ADDRESS: "0xc296f1622C4c26578B47183685D52c778fd0c295"
      VITE_ROLLUP_A_UNISWAP_V3_MIGRATOR_ADDRESS: "0x24de895D52f5C2932E007FC6EEA8E6A46901a120"
      VITE_ROLLUP_A_UNISWAP_V3_STAKER_ADDRESS: "0xF0bf386ec3cD51daA5BaC74e06a897C9D4d02619"
      VITE_ROLLUP_A_UNISWAP_QUOTER_V2_ADDRESS: "0x6Df15bfF5Ac8A9B24536D5FD7c7b9f95ed94A774"
      VITE_ROLLUP_A_UNISWAP_SWAP_ROUTER02: "0x78C4608838E0AB4406920c77c22b925A896Fa610"
      VITE_ROLLUP_B_UNISWAP_V3_CORE_FACTORY_ADDRESS: "0xC6E64650f810589fC59e2a663f4fD3253523E1C5"
      VITE_ROLLUP_B_UNISWAP_MULTICALL2_ADDRESS: "0x652F8630b21Ce126Eed9425f23B9b1C71f4f4669"
      VITE_ROLLUP_B_UNISWAP_PROXY_ADMIN_ADDRESS: "0xF85309200ABe42B03b0bE7C4dE3a36f905eaF008"
      VITE_ROLLUP_B_UNISWAP_TICK_LENS_ADDRESS: "0x4F04A98376ECec41e8Ba9d38a912097668B9FD9c"
      VITE_ROLLUP_B_UNISWAP_NFT_DESCRIPTOR_LIBRARY_ADDRESS_V1_3_0: "0x7289aB331Eb0ea43f0D6379761B5ccD34B955B73"
      VITE_ROLLUP_B_UNISWAP_NONFUNGIBLE_TOKEN_POSITION_DESCRIPTOR_ADDRESS_V1_3_0: "0x51f8397B783EBa036208f40d54d46A5F5A3BEa7f"
      VITE_ROLLUP_B_UNISWAP_DESCRIPTOR_PROXY_ADDRESS: "0x9AeeD06e5CDBa2D1FF0ff12e8a99Ba85cD202BD1"
      VITE_ROLLUP_B_UNISWAP_NONFUNGIBLE_TOKEN_POSITION_MANAGER_ADDRESS: "0x51ef42e7B2C71E3C4A42603ADbfb565F7fB9c3F6"
      VITE_ROLLUP_B_UNISWAP_V3_MIGRATOR_ADDRESS: "0x101631194dD8F541B173178effb795c2eFa057eE"
      VITE_ROLLUP_B_UNISWAP_V3_STAKER_ADDRESS: "0x323A7da11ac1eDd6acb125b0145A30729583e298"
      VITE_ROLLUP_B_UNISWAP_QUOTER_V2_ADDRESS: "0x65D8553A3845281BE9AA8323f05719E33a39EfdA"
      VITE_ROLLUP_B_UNISWAP_SWAP_ROUTER02: "0xB37Dc895749506b3b664bC54d7AEA86Afbe2A07A"

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install packages
        run: pnpm install

      - name: Setup swap
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 4

      - name: Run stage webapp build
        env:
          NODE_OPTIONS: --max-old-space-size=2048
        run:
          pnpm -r --workspace-concurrency=1 build

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/stage'
        uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3
        with:
          role-to-assume: ${{ secrets.COMPOSE_WEB_DEMO_STAGE_AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload files to S3
        if: github.ref == 'refs/heads/stage'
        run: |
          aws s3 cp ./build s3://${{ secrets.COMPOSE_WEB_DEMO_STAGE_AWS_S3_BUCKET }} --recursive
