name: Build & deploy

on:
  push:
    branches:
      - 'stage'

  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      VITE_ROLLUP_A_CHAIN_ID: "77777"
      VITE_ROLLUP_B_CHAIN_ID: "88888"
      VITE_HOODI_CHAIN_ID: "560048"
      VITE_ROLLUP_A_RPC_HTTP: '["https://rollup-rpc-1.stage.ops.ssvlabsinternal.com"]'
      VITE_ROLLUP_B_RPC_HTTP: '["https://rollup-rpc-2.stage.ops.ssvlabsinternal.com"]'
      VITE_HOODI_RPC_HTTP: '["https://ethereum-hoodi-rpc.publicnode.com/d8a2cc6e7483872e917d7899f9403d738b001c80e37d66834f4e40e9efb54a27"]'
      VITE_MAINNET_RPC_HTTP: '["https://eth.llamarpc.com"]'
      VITE_POLYGON_RPC_HTTP: '["https://polygon-rpc.com"]'
      VITE_ROLLUP_A_BLOCK_EXPLORER_URL: "https://blockscout-rollup-1.stage.ops.ssvlabsinternal.com/"
      VITE_ROLLUP_B_BLOCK_EXPLORER_URL: "https://blockscout-rollup-2.stage.ops.ssvlabsinternal.com/"
      VITE_PAYMASTER_URL: "https://paymaster.stage.ops.ssvlabsinternal.com"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install packages
        run: pnpm install

      - name: Setup swap
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 4

      - name: Run stage webapp build
        env:
          NODE_OPTIONS: --max-old-space-size=2048
        run:
          pnpm -r --workspace-concurrency=1 build

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/stage'
        uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3
        with:
          role-to-assume: ${{ secrets.COMPOSE_WEB_DEMO_STAGE_AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload files to S3
        if: github.ref == 'refs/heads/stage'
        run: |
          aws s3 cp ./build s3://${{ secrets.COMPOSE_WEB_DEMO_STAGE_AWS_S3_BUCKET }} --recursive
