name: Build & deploy

on:
  push:
    branches:
      - 'stage'

  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Load .env file
        uses: xom9ikk/dotenv@ac290ca23a42155a0cba1031d23afa46240116a9 # v2.3.0
        with:
          path: ./

      - name: Run stage webapp build
        env:
          TEST: test
        run:
          yarn build

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/stage'
        uses: aws-actions/configure-aws-credentials@50ac8dd1e1b10d09dac7b8727528b91bed831ac0 # v3
        with:
          role-to-assume: ${{ secrets.COMPOSE_WEB_DEMO_STAGE_AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload files to S3
        if: github.ref == 'refs/heads/stage'
        run: |
          aws s3 cp ./dist s3://${{ secrets.COMPOSE_WEB_DEMO_STAGE_AWS_S3_BUCKET }} --recursive
